# Generated by Django 5.1.7 on 2025-03-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('hub', 'Hub principal'), ('relay', 'Relais intermédiaire'), ('client', 'Client final')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('camion', 'Camion'), ('utilitaire', 'Utilitaire'), ('refrigere', 'Réfrigéré')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('availability_start', models.TimeField()),
                ('availability_end', models.TimeField()),
                ('cost_per_km', models.FloatField(help_text='Coût en FCFA par km')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance en kilomètres')),
                ('base_time', models.FloatField(help_text='Temps de parcours nominal en minutes')),
                ('cost', models.FloatField(help_text='Coût monétaire de la traversée')),
                ('road_type', models.IntegerField(choices=[(0, 'Asphalte'), (1, 'Latérite'), (2, 'Piste')])),
                ('reliability', models.FloatField(help_text='Fiabilité [0-1]')),
                ('restrictions', models.IntegerField(help_text='Ex: 1 = fragile, 2 = express, 4 = poids_max')),
                ('time_variation_morning', models.FloatField(default=1.0)),
                ('time_variation_afternoon', models.FloatField(default=1.0)),
                ('time_variation_night', models.FloatField(default=1.0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='network.node')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='network.node')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('fragile', 'Fragile')], max_length=10)),
                ('deadline', models.TimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_destinations', to='network.node')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_origins', to='network.node')),
            ],
        ),
    ]
